title: Elijah Arnsworth's Cybersecurity Projects
description: This repository showcases my cybersecurity projects, including security automation scripts, SIEM use case development, vulnerability management workflows, compliance monitoring tools, and cloud security implementations. 
Each project demonstrates hands-on experience with threat detection, incident response, and security best practices.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
